### PR TITLE
Remove pixell sharp dependency

### LINKED ISSUE #178: Error while returning a CAR map
I am describing here an issue that I ran into while trying to return a CAR map using `pysm3.apply_smoothing_and_coord_transform`

I find specifically the error originates when _template.py_ tries to import `pixell.sharp` here:
https://github.com/galsci/pysm/blob/b15425310e8c3ffae4a94b08ea8c8aa7c61b8a09/pysm3/models/template.py#L19-L24

Full traceback error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 sim_map_rot = pysm3.apply_smoothing_and_coord_transform(sim_map, rot=hp.Rotator(coord="GC"),
      2                                                         output_car_resol =  0.25 * u.arcmin,
      3                                                        return_healpix= False,
      4                                                        return_car=True)

File /venvs/toast-venv/lib/python3.10/site-packages/pysm3/models/template.py:261, in apply_smoothing_and_coord_transform(input_map, fwhm, rot, lmax, output_nside, output_car_resol, return_healpix, return_car, input_alm, map2alm_lsq_maxiter, map_dist)
    259 if return_car:
    260     log.info("Alm to map CAR")
--> 261     shape, wcs = pixell.enmap.fullsky_geometry(
    262         output_car_resol.to_value(u.radian),
    263         dims=(3,),
    264         variant="fejer1",
    265     )
    266     ainfo = pixell.sharp.alm_info(lmax=lmax)
    267     output_maps.append(
    268         u.Quantity(
    269             pixell.curvedsky.alm2map(
   (...)
    274         )
    275     )

AttributeError: 'NoneType' object has no attribute 'enmap'
```

This happens because `import pixell.sharp` fails and `pixell = None` is assigned. I do not find pixell.sharp here:
https://github.com/simonsobs/pixell/tree/master/pixell

##### I would like to get a pysm3 map in CAR format, and would greatly appreciate your suggestions in case I am going wrong in the steps. Thanks
----------------------------------------------------------------------------------------------------------------------------------

Some additional package version info:
```

import pixell
print(f"pixell version : {pixell.__version__}")
print(f"pysm3 version : {pysm3.__version__}")

import pixell.sharp
pixell version : 0.23.8
pysm3 version : 3.4.0
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 5
      2 print(f"pixell version : {pixell.__version__}")
      3 print(f"pysm3 version : {pysm3.__version__}")
----> 5 import pixell.sharp

ModuleNotFoundError: No module named 'pixell.sharp'
```

### PR DESCRIPTION
**Pull request by msyriac**
This fixes #178

### CODE REVIEW

**Comment by zonca** [comment]
@msyriac feel free to update minimum python in Github Action or notify me to take care of that

**Comment by msyriac** [comment]
I have now, but there seems to be a numpy related error. I might not have time to look into this until next week!

**Comment by itrharrison** [comment]
I think the problem is that pixell's setup.py imports various numpy things but that requirement isn't satisfied when the setup gets run.

Adding numpy to the pysm `install_requires` to include numpy seems to fix (but ofc I can't push to Mat's fork).

**Comment by zonca** [comment]
@itrharrison if you'd like to open another PR and fix this it would be much appreciated!

**Comment by zonca** [comment]
@itrharrison do you have a branch where you tested this?

**Comment by itrharrison** [comment]
No, sorry, I have been trying but no matter where I add numpy the same problem appears. You can see here:
https://github.com/itrharrison/pysm/pull/1/files

I guess the other option would be for pixell to remove the numpy imports from its setup.py

**Comment by zonca** [comment]
Thank you very much for your help with this. I was wondering, is it possible this has something to do with numpy 2.0?
Does it make a difference if we set to avoid numpy.2?

**Comment by zonca** [comment]
@itrharrison maybe we should open a PR on pixell implementing this? @msyriac?
https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py

**Comment by zonca** [comment]
my hope is that putting `numpy` in `setup_requires` on `pixell` fixes this issue

**Comment by zonca** [comment]
@itrharrison would you like to create a branch of pixell with this fix, then setup Github Actions in your branch of PySM to install pixell from that git branch and see if everything magically works (I know I'm an optimist!).
If so, we (meaning you of course) can then contribute this fix to `pixell`.

**Pull request merged**
