### PR TITLE
GNILC dust templates with polarization fraction tensor

### PR DESCRIPTION
**Pull request by zonca**
View and comment on the notebook at: https://app.reviewnb.com/healpy/pysm/pull/72/files/

The plan as suggested by Jacques Delabrouille is to add small scales fluctuations directly in needlet space, and 
Mathieu Remazeilles is working on it.

However I think it is useful to have a simpler model to compare to, so the plan here is to fit for a high-ell slope to the GNILC maps and then add small scale fluctuations.
The difference with PySM 2 is that now I am using the log of the polarization fraction tensor as suggested by Andrei Frolov, it is based on polarization fraction, so we get the polarization fluctuations automatically scale with amplitude of the large scale emission:

image

### CODE REVIEW

**Comment by zonca** [comment]
## Masking

**Comment by zonca** [comment]
## Resolution of the GNILC maps

* see the `gnilc_resolution.ipynb` notebook at https://app.reviewnb.com/healpy/pysm/pull/72/files/

image

**Comment by zonca** [comment]
## Fitting using GNILC R3

In the notebook attached to this PR I am loading the R3 maps (also for intensity), building the log of the polarization fraction tensor and fitting a slope to that.

I select manually a range of ell [100-300] which is clean from large scale fluctuations and before emission starts to flatten due to noise (I believe).

image
image
image

And that is exactly the problem, what section of the spectrum do we want to use for fitting?

**Comment by brandonshensley** [comment]
A few quick thoughts, but hopefully others can chime in:

1. The masking looks good. Things get complicated (and possibly qualitatively different) too near the Galactic plane, so best to mask it even though there is a lot of signal there.
2. Hopefully Andrei has thoughts re mixing resolutions. Definitely sounds non-ideal, but it would also be a shame to smooth the I maps.
3. Is the reason that the TT spectrum flattens at the same ell as EE and BB just that you are using the polarization tensor formalism? It looks like the PySM2 model used ells well below 100 for their fits (see [Figure 5](https://ui.adsabs.harvard.edu/abs/2017MNRAS.469.2821T/abstract)). Are the differences due to the maps used or the polarization tensor approach?

Thank you for putting this together!

**Comment by zonca** [comment]
> A few quick thoughts, but hopefully others can chime in:
> 
> 1. The masking looks good. Things get complicated (and possibly qualitatively different) too near the Galactic plane, so best to mask it even though there is a lot of signal there.

very good thanks

> 2. Hopefully Andrei has thoughts re mixing resolutions. Definitely sounds non-ideal, but it would also be a shame to smooth the I maps.

ok wrote him email about this

> 3. Is the reason that the TT spectrum flattens at the same ell as EE and BB just that you are using the polarization tensor formalism? It looks like the PySM2 model used ells well below 100 for their fits (see [Figure 5](https://ui.adsabs.harvard.edu/abs/2017MNRAS.469.2821T/abstract)). Are the differences due to the maps used or the polarization tensor approach?

I'm investigating, I'll update this answer with what I find.

**Comment by zonca** [comment]
## Power spectrum of the GNILC R2 II map

image

**Comment by brandonshensley** [comment]
Do we understand the features in the spectrum above ell of 1000? Or do we not use that part anyway so it doesn't matter?

**Comment by zonca** [comment]
I have a new notebook with lots of improvements, will post on Monday

**Comment by zonca** [comment]
ok,
I have fixed the issue using the polarization fraction tensor, now the fit looks better (now properly in log-log):

image
image
image

I changed the mask, I noticed that GNILC had already sources removed, so chose a large galactic mask (`GAL060` from HFI PR2):

image

This was due to the fact that when I want to remove the small scales from the GNILC temperature map, then when I apply the mask and run NaMaster, I see residual power at high-ell, this is improved if I use a mask which has no point sources and I don't apply too steep a cut (I am using a sigmoid so I can tweak the steepness of the cut).
Even now I can see the effect (please send suggestions on how to improve here, I would like to apply a steeper cut):

image

However the residuals are finally small enough that the output spectra look fine (before they showed a step in the II output spectrum around ell = 1400 because the residual small scale signal from the large scale signal map was added to the actual simulated gaussian small scales:

image
image
image

The full notebook with the analysis is at:

https://nbviewer.jupyter.org/gist/zonca/d00d3d2e17d902e5aac6f80e4c9f20f4

If anyone has suggestions on how to reduce the leaking of power to high ell, I would use a sharper transition between the input map and the gaussian realization, otherwise I think this is acceptable and I can produce the final templates for inspection from other people.

**Comment by giuspugl** [comment]
This is great! Are the spectra shown here in real units or in the pol. fract. tensor ones?

**Comment by zonca** [comment]
all of them in pol frac tensor, I'll also add a summary plot in standard IQU at the end of the notebook

**Comment by zonca** [comment]
## TE

During the CMB-S4 meeting there was a mention of PySM 3 not having TE in the galactic models.

* does it make sense even if we have different resolutions and temperature/polarization maps from different releases?
* also, in the polarization fraction formalism, TE is related to how the T emission is correlated with the polarization fraction. Is this fine?

I made a first attempt at the fit:

image

the problem is that when I try to add the small scales generated using this fit, the polarization maps have way too much power and are completely off:

image

I'll keep investigating but it would be useful to have a general opinion about this and an answer to the 2 questions above.

**Comment by bthorne93** [comment]
Hi Andrea, I've been taking another look at this model, and was wondering about something. In this model we care about the polarization fraction, and so it is important to get the zero level of the intensity maps right. The GNILC maps do not seem to remove the CIB monopole, and get the overall zero-level contribution from dust slightly wrong (according to section 2.2 of [1807.06212](https://arxiv.org/pdf/1807.06212.pdf)). 

I've taken a look at the effect of removing at least the CIB monopole from the GNILC intensity map, and combining this with gaussian realizations of Frolov (q, u) to produce (Q, U) with power tuned to the level in the BK maps (4.7 uK at ell=80). Whether or not you include the monopole in the intensity map seems to have a large qualitative effect on the simulations for a given power level, at these higher latitudes. 

The small scale realizations you're doing here are slightly different, and I'm not sure yet what effect this has, if any. Have you already considered this?

**Comment by zonca** [comment]
no, haven't considered this at all, can you please share the code you used to fix the monopole level? or modify my notebook to incorporate that?

**Comment by zonca** [comment]
current issues slides: https://us02st1.zoom.us/web_client/ehjzr5/html/externalLinkPage.html?ref=https://docs.google.com/presentation/d/19Tcg_jccTgSg8KtZgf5PT0R2MVNFdl5_PM5mJjnN0EM/edit?usp=sharing

* @bthorne93 will help with the monopole, also Jacques can provide maps for comparison of zero level
* for covariance, start just using the IQU covariance itself
* once those 2 are fixed, evaluate again TE, also send to Jacques to see if he finds anything wrong in the computation

**Comment by zonca** [comment]
@bthorne93 just a reminder to send me details about fixing the monopole level.

**Comment by bthorne93** [comment]
Based on Section 2.2 of [Planck 2018: XII](https://arxiv.org/pdf/1807.06212.pdf), the contributions to the monopole in the 353 GHz GNILC intensity map are CIB and dust. They remove the CIB contribution, and apply some process to improve on the estimate of the dust monopole the maps already contained.

The numbers for each contribution can be found in Table 12 of [Planck 2018: III](https://arxiv.org/abs/1807.06207), which I've pasted below. This seems to indicate there is a relevant (but very small) contribution from zodiacal emission as well, which is not discussed in XII.

The simplest first thing to do is just remove the CIB contribution, for which I've been using the number in Table 12: 0.13 MJy/sr at 353 GHz. Perhaps we also need to remove zodiacal emission, and perhaps we also need to refine the dust monopole model as was done in XII.   

Screen Shot 2021-04-26 at 10 27 15 AM

**Comment by zonca** [comment]
## Resolution with GAL080 mask

image

```
0,27.70%
10,0.04%
15,0.44%
20,4.26%
30,16.09%
60,45.93%
80,5.54%
```

**Comment by zonca** [comment]
ok, I have made a few changes:

* Using GAL080 instead of GAL060 so we have more sky coverage (same used in PySM 2)
* Using 2 degree apodization masks as provided by Planck
* Removed TE: I believe that the output maps will have TE correlations anyway because of transforming back from polarization fraction tensor to IQU
* Fixed monopole as suggested by @bthorne93 
* Focusing on lower ell range for fitting both in T and P
* Use cosmic variance in the fitting
* Using a sharper sigmoid for the transition

Need to do:

* T small scales are uniform across the sky, they should be multiplied by a normalized smoothed T map?
* Understand why fitted polarization slopes are so flat

the full notebook executed is at:

https://nbviewer.jupyter.org/gist/zonca/b398f85f701088ba60e3e66a20e0f48f

## Spectra fitting plots

image
image
image

Fitted slopes are very close to zero: 

```
'TT': -1.001
'EE': -0.053
'BB': -0.012
```

**Comment by zonca** [comment]
Thanks @brandonshensley and @seclark for the chat today, some notes:

* fitted slopes are very close to zero, it could be because we are using variable resolution, we could either try to use the unires version at 80 arcmin or directly switch to 353GHz where it is easier to control the beam. So we could use GNILC temperature which is good because it has less contamination from CIB. Those are all options to explore
* the sigmoid transition is possibly too sharp and could cause a strange feature in the spectrum, better use a standard beam/inverse beam.
* The Planck paper about dust has fitted slopes, which are for example around -0.5 for BB (they quote -2.5 but then add 2 in the modelling). So another option is to keep that slope and just fit for the amplitude (this is even better if we are using the 353 maps in polarization).
* As noted above, the small scales for temperature are uniform, they should be instead scaled for total amplitude normalized properly.
* It looks fine to skip doing inverse noise weighting, signal is not uniform, so this could create issues in the spectra
* I had previously ran a simple simulation to check that if you take the log of a powerlaw the new map has the same slope in the spectrum: https://gist.github.com/dd2a68b424333f14d37b47cc6df75ebf

**Comment by zonca** [comment]
see #74

**Pull request closed without merging**
