### PR TITLE
JOSS paper

### PR DESCRIPTION
**Pull request by zonca**
- authors and start of bibliography
- first full draft

### CODE REVIEW

**Comment by zonca** [comment]
@bthorne93 I have a rough draft, please take a look.

the compiled PDF is attached as an artifact of the Paper Draft GitHub action.

**Comment by zonca** [comment]
@bthorne93 also please make a PR on my `zonca/paper` branch for your affiliation

**Comment by bthorne93** [comment]
Looks good, opened a [PR](https://github.com/zonca/pysm/pull/4#issue-690106654) on your fork with some small language changes.

**Comment by zonca** [comment]
thanks @bthorne93!

@NicolettaK can you make a PR to the `paper` branch with your affiliation and do a quick review of the paper?
compiled PDF is at https://github.com/healpy/pysm/suites/3240998740/artifacts/75222461

**Comment by NicolettaK** [comment]
Done in https://github.com/zonca/pysm/pull/5#, just added my affiliations. Everything looks good to me! Thanks for this @zonca

**Comment by zonca** [comment]
Thanks @NicolettaK, latest draft at:

https://github.com/healpy/pysm/suites/3247846457/artifacts/75440225

**Review by bthorne93 — APPROVED** [review]

**Pull request merged**
