### PR TITLE
Synchrotron, new small scales

### PR DESCRIPTION
**Pull request by zonca**
- save kernel name to execute with papermill
- notebook executed by @giuspugl, black-formatted
- add more documentation to notebook

### CODE REVIEW

**Comment by zonca** [comment]
@giuspugl there was no change in the modulation of temperature, so I kept the same `beta` for synchrotron of the last release, please advise if you would like instead to implement the 2 slopes approach with `beta` as well.

**Comment by zonca** [comment]
## Beta synchrotron

image
image
image

**Comment by zonca** [comment]
Test s5 vs s6 passes at NERSC both at 23 and 44 GHz

**Comment by giuspugl** [comment]
> there was no change in the modulation of temperature, so I kept the same beta for synchrotron of the last  release
This is correct, both temperature small scales and beta maps are left untouched, it is fine to keep beta and curvature templates as they were before. Please just make sure that the new modulation map for polarization small scales   is updated .

**Pull request merged**
